apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pokemon-react
  annotations:
    github.com/project-slug: alexandrejuk/pokemon-react
spec:
  type: service
  owner: team-levelup
  lifecycle: experimental
