version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              if: $CIRCLE_BRANCH == 'maste'
              command: REACT_APP_PAGARME_ENVIRONMENT=test
            - run: echo $REACT_APP_PAGARME_ENVIRONMENT

workflows:
    build-and-test:
      jobs:
        - build-and-test