version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
      - run: echo $CIRCLE_BRANCH
      # - when:
      #     condition: $CIRCLE_BRANCH == 'master'
      #     steps:
      #       - run: echo "Estou na Master"
      # - unless:
      #     condition: << parameters.preinstall-foo >>
      #     steps:
      #       - run: echo "don't preinstall
workflows:
    build-and-test:
      jobs:
        - build-and-test