version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
      - when:
          condition: $CIRCLE_CI == 'master'
          steps:
            - run: echo export REACT_APP_PAGAR_ENVIRONMENT=live
      - unless:
          condition: $CIRCLE_CI == 'staging'
          steps:
            - run: echo export REACT_APP_PAGAR_ENVIRONMENT=test
workflows:
    build-and-test:
      jobs:
        - build-and-test