name: Build Deploy beta

on:
  push:
    tags:
      -  v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  deploy:
    name: 'Pokemon react build and deploy beta'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true