name: Build Deploy Prod

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    name: 'Pokemon react build and deploy production'
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: ./build
          deploy-token: ${{ secrets.MY_TOKEN_SECRET }}